package br.com.w4solution.cob4.services.planejamento;
import br.com.w4solution.cob4.domain.*;import br.com.w4solution.cob4.dto.planejamento.DashboardDTO;import br.com.w4solution.cob4.repositories.*;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.*;import java.time.*;import java.util.*;
@Service public class DashboardService{
	private static final List<Cobranca.Status> ATIVOS=List.of(Cobranca.Status.ABERTA,Cobranca.Status.EM_ANDAMENTO);
	private final CobrancaRepository cobrancas;private final AtendimentoRepository atendimentos;private final SincronizacaoRbxExecucaoRepository sync;
	public DashboardService(CobrancaRepository c,AtendimentoRepository a,SincronizacaoRbxExecucaoRepository s){cobrancas=c;atendimentos=a;sync=s;}
	@Transactional(readOnly=true) public DashboardDTO.Executivo executivo(OffsetDateTime inicio,OffsetDateTime fim){var status=cobrancas.resumirPorStatus();long ativos=status.stream().filter(x->Set.of("ABERTA","EM_ANDAMENTO").contains(x.getChave())).mapToLong(CobrancaRepository.ResumoGrupo::getQuantidade).sum();BigDecimal saldo=status.stream().filter(x->Set.of("ABERTA","EM_ANDAMENTO").contains(x.getChave())).map(CobrancaRepository.ResumoGrupo::getValor).reduce(BigDecimal.ZERO,BigDecimal::add);long encerrados=status.stream().filter(x->Set.of("ENCERRADA","PAGA","CANCELADA").contains(x.getChave())).mapToLong(CobrancaRepository.ResumoGrupo::getQuantidade).sum();return new DashboardDTO.Executivo(ativos,saldo,encerrados,atendimentos.countByRealizadoEmBetween(inicio,fim));}
	@Transactional(readOnly=true) public DashboardDTO.Operacao operacao(){return new DashboardDTO.Operacao(itens(cobrancas.resumirPorStatus()),itens(cobrancas.resumirPorPrioridade(ATIVOS)),itens(cobrancas.resumirPorFaixa(ATIVOS)));}
	@Transactional(readOnly=true) public DashboardDTO.Equipe equipe(OffsetDateTime inicio,OffsetDateTime fim){var ats=atendimentos.produtividadeEntre(inicio,fim).stream().collect(java.util.stream.Collectors.toMap(AtendimentoRepository.ProdutividadeOperador::getOperador,AtendimentoRepository.ProdutividadeOperador::getQuantidade));var lista=cobrancas.resumirPorResponsavel(ATIVOS).stream().map(x->new DashboardDTO.Produtividade(x.getChave(),x.getQuantidade(),ats.getOrDefault(x.getChave(),0L))).toList();return new DashboardDTO.Equipe(lista);}
	@Transactional(readOnly=true) public DashboardDTO.Sla sla(){var agora=OffsetDateTime.now();var ativas=cobrancas.findByCriadaEmBeforeAndStatusIn(agora,ATIVOS);long pausadas=ativas.stream().filter(c->c.getSlaPausadoEm()!=null).count();long vencidas=ativas.stream().filter(c->c.getSlaPausadoEm()==null&&c.getUltimaMovimentacaoEm().plusHours(c.getSlaHoras()).isBefore(agora)).count();return new DashboardDTO.Sla(ativas.size()-pausadas-vencidas,vencidas,pausadas);}
	@Transactional(readOnly=true) public DashboardDTO.Integracoes integracoes(){return new DashboardDTO.Integracoes(sync.countByStatus(SincronizacaoRbxExecucao.Status.SUCESSO),sync.countByStatus(SincronizacaoRbxExecucao.Status.FALHA),0);}
	private List<DashboardDTO.Item> itens(List<CobrancaRepository.ResumoGrupo> v){return v.stream().map(x->new DashboardDTO.Item(x.getChave(),x.getQuantidade(),x.getValor())).toList();}
}
