import {useState} from 'react';
import {Alert,Box,Button,Card,CardContent,Chip,Divider,Grid,Stack,TextField,Typography} from '@mui/material';
import {enviarAnexo} from '@/services/atendimentos';
import {simularAcordo,criarAcordo,listarAcordos,decidirAcordo,ativarAcordo,registrarPagamentoFinanceiro,listarPagamentos,confirmarPagamento,estornarPagamento,conciliarFinanceiro} from '@/services/financeiro';
const hoje=new Date().toISOString().slice(0,10);const moeda=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function FinanceiroOperacionalPage(){
 const[referencia,setReferencia]=useState('');const[acordos,setAcordos]=useState([]);const[pagamentos,setPagamentos]=useState([]);const[simulacao,setSimulacao]=useState(null);const[erro,setErro]=useState('');const[aviso,setAviso]=useState('');const[conciliacao,setConciliacao]=useState(null);
 const[proposta,setProposta]=useState({cobrancas:'',descontoPercentual:0,entrada:0,parcelas:1,primeiroVencimento:hoje,justificativa:'Negociacao registrada no atendimento'});
 const[pagamento,setPagamento]=useState({acordoProtocolo:'',valor:'',dataPagamento:hoje,origem:'MANUAL',referenciaExterna:'',observacao:''});const[arquivo,setArquivo]=useState(null);
 const payload=()=>({...proposta,cobrancas:proposta.cobrancas.split(',').map(v=>v.trim()).filter(Boolean),descontoPercentual:Number(proposta.descontoPercentual),entrada:Number(proposta.entrada),parcelas:Number(proposta.parcelas)});
 const executar=async(fn,sucesso)=>{setErro('');setAviso('');try{const r=await fn();if(sucesso)setAviso(sucesso);return r;}catch(e){setErro(e.response?.data?.message||e.response?.data?.erro||'Operacao financeira nao concluida.');return null;}};
 const carregar=async()=>{if(!referencia)return;const r=await executar(()=>Promise.all([listarAcordos(referencia),listarPagamentos(referencia)]));if(r){setAcordos(r[0]);setPagamentos(r[1]);}};
 const criar=async()=>{const r=await executar(()=>criarAcordo(payload()),'Proposta criada.');if(r){setSimulacao(r);setReferencia(payload().cobrancas[0]);await carregar();}};
 const registrar=async()=>{if(!arquivo||!referencia){setErro('Informe a cobranca e selecione o comprovante.');return;}const an=await executar(()=>enviarAnexo(referencia,arquivo,'COMPROVANTE'));if(!an)return;const r=await executar(()=>registrarPagamentoFinanceiro({...pagamento,cobrancaReferencia:referencia,valor:Number(pagamento.valor),comprovanteId:an.id,chaveIdempotencia:crypto.randomUUID()}),'Pagamento registrado e aguardando confirmacao.');if(r)await carregar();};
 return <Stack spacing={3}><Box><Typography variant="h4" fontWeight={700}>Operacao financeira</Typography><Typography color="text.secondary">Negociacao, aprovacao, parcelas, pagamentos, comprovantes e conciliacao.</Typography></Box>
 {erro&&<Alert severity="error" onClose={()=>setErro('')}>{erro}</Alert>}{aviso&&<Alert severity="success" onClose={()=>setAviso('')}>{aviso}</Alert>}
 <Card><CardContent><Stack direction={{xs:'column',md:'row'}} spacing={2}><TextField fullWidth label="Referencia da cobranca" value={referencia} onChange={e=>setReferencia(e.target.value)}/><Button variant="contained" onClick={carregar}>Consultar jornada</Button><Button variant="outlined" onClick={async()=>setConciliacao(await executar(conciliarFinanceiro,'Conciliacao executada.'))}>Conciliar RBX</Button></Stack>{conciliacao&&<Alert sx={{mt:2}} severity={conciliacao.divergentes?'warning':'success'}>{conciliacao.conciliados} conciliado(s), {conciliacao.divergentes} divergente(s), {conciliacao.pendentes} pendente(s).</Alert>}</CardContent></Card>
 <Card><CardContent><Stack spacing={2}><Typography variant="h6">Nova negociacao</Typography><Divider/><Grid container spacing={2}>
 {[["cobrancas","Cobrancas separadas por virgula"],["descontoPercentual","Desconto (%)","number"],["entrada","Entrada","number"],["parcelas","Parcelas","number"],["primeiroVencimento","Primeiro vencimento","date"],["justificativa","Justificativa"]].map(([campo,label,tipo])=><Grid key={campo} size={{xs:12,md:campo==='cobrancas'||campo==='justificativa'?6:3}}><TextField fullWidth size="small" type={tipo||'text'} label={label} value={proposta[campo]} InputLabelProps={tipo==='date'?{shrink:true}:undefined} onChange={e=>setProposta(p=>({...p,[campo]:e.target.value}))}/></Grid>)}</Grid>
 <Stack direction="row" spacing={1} justifyContent="flex-end"><Button variant="outlined" onClick={async()=>setSimulacao(await executar(()=>simularAcordo(payload())))}>Simular</Button><Button variant="contained" onClick={criar}>Criar proposta</Button></Stack>
 {simulacao&&<Alert severity="info">Principal {moeda(simulacao.principal)} + juros {moeda(simulacao.juros)} + multa {moeda(simulacao.multa)} - desconto {moeda(simulacao.desconto)} = <b>{moeda(simulacao.valorNegociado)}</b>. Status: {simulacao.status}.</Alert>}
 </Stack></CardContent></Card>
 <Card><CardContent><Stack spacing={2}><Typography variant="h6">Acordos e aprovacoes</Typography>{!acordos.length&&<Typography color="text.secondary">Consulte uma cobranca para visualizar acordos.</Typography>}{acordos.map(a=><Stack key={a.id} spacing={1} borderBottom={1} borderColor="divider" py={1}><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between"><Box><Typography fontWeight={700}>{a.protocolo} <Chip size="small" label={a.status}/></Typography><Typography variant="body2">{moeda(a.valorNegociado)} · política v{a.politicaVersao} · {a.quantidadeParcelas} parcela(s)</Typography></Box><Stack direction="row" spacing={1}>{a.status==='AGUARDANDO_APROVACAO'&&<><Button size="small" onClick={async()=>{await executar(()=>decidirAcordo(a.protocolo,true,'Aprovado'),'Acordo aprovado.');carregar();}}>Aprovar</Button><Button size="small" color="error" onClick={async()=>{await executar(()=>decidirAcordo(a.protocolo,false,'Fora da politica'),'Acordo rejeitado.');carregar();}}>Rejeitar</Button></>}{a.status==='APROVADO'&&<Button size="small" onClick={async()=>{await executar(()=>ativarAcordo(a.protocolo),'Acordo ativado.');carregar();}}>Ativar</Button>}</Stack></Stack><Stack direction="row" spacing={1} flexWrap="wrap">{a.parcelas.map(p=><Chip key={p.id} size="small" label={`${p.numero}: ${moeda(p.total)} - ${p.status}`}/>)}</Stack></Stack>)}</Stack></CardContent></Card>
 <Card><CardContent><Stack spacing={2}><Typography variant="h6">Registrar pagamento</Typography><Divider/><Grid container spacing={2}>
 <Grid size={{xs:12,md:3}}><TextField fullWidth size="small" label="Protocolo do acordo (opcional)" value={pagamento.acordoProtocolo} onChange={e=>setPagamento(p=>({...p,acordoProtocolo:e.target.value}))}/></Grid><Grid size={{xs:12,md:2}}><TextField fullWidth size="small" type="number" label="Valor" value={pagamento.valor} onChange={e=>setPagamento(p=>({...p,valor:e.target.value}))}/></Grid><Grid size={{xs:12,md:2}}><TextField fullWidth size="small" type="date" label="Data" value={pagamento.dataPagamento} InputLabelProps={{shrink:true}} onChange={e=>setPagamento(p=>({...p,dataPagamento:e.target.value}))}/></Grid><Grid size={{xs:12,md:3}}><TextField fullWidth size="small" label="Referencia RBX" value={pagamento.referenciaExterna} onChange={e=>setPagamento(p=>({...p,referenciaExterna:e.target.value}))}/></Grid><Grid size={{xs:12,md:2}}><Button component="label" variant="outlined" fullWidth>Comprovante<input hidden type="file" onChange={e=>setArquivo(e.target.files?.[0])}/></Button></Grid></Grid><Typography variant="caption">{arquivo?.name||'Nenhum comprovante selecionado'}</Typography><Button variant="contained" onClick={registrar}>Registrar pagamento</Button>
 {pagamentos.map(p=><Stack key={p.id} direction={{xs:'column',md:'row'}} justifyContent="space-between" borderTop={1} borderColor="divider" pt={1}><Typography>#{p.id} · {moeda(p.valor)} · {p.status}{Number(p.creditoExcedente)>0&&` · credito ${moeda(p.creditoExcedente)}`}</Typography><Stack direction="row" spacing={1}>{p.status==='PENDENTE'&&<Button size="small" onClick={async()=>{await executar(()=>confirmarPagamento(p.id),'Pagamento confirmado.');carregar();}}>Confirmar</Button>}{['CONFIRMADO','CONCILIADO'].includes(p.status)&&<Button size="small" color="error" onClick={async()=>{await executar(()=>estornarPagamento(p.id,'Estorno operacional'),'Pagamento estornado.');carregar();}}>Estornar</Button>}</Stack></Stack>)}</Stack></CardContent></Card>
 </Stack>}
