create table politicas_financeiras (
    id bigint generated by default as identity primary key, versao integer not null, vigente boolean not null,
    juros_tipo varchar(20) not null, juros_percentual numeric(9,6) not null, juros_periodicidade varchar(20) not null,
    juros_inicio varchar(30) not null, juros_carencia_dias integer not null, juros_sobre_multa boolean not null,
    juros_limite_percentual numeric(9,6), multa_tipo varchar(20) not null, multa_valor numeric(19,6) not null,
    multa_limite numeric(19,2), multa_inicio varchar(30) not null, multa_carencia_dias integer not null,
    multa_recorrente boolean not null, casas_decimais integer not null, metodo_arredondamento varchar(30) not null,
    momento_arredondamento varchar(30) not null, destino_centavos varchar(30) not null,
    maximo_parcelas integer not null, valor_minimo_parcela numeric(19,2) not null,
    intervalo_parcelas_dias integer not null, ajuste_dia_nao_util varchar(30) not null,
    entrada_obrigatoria boolean not null, entrada_percentual_minimo numeric(9,6) not null,
    entrada_valor_minimo numeric(19,2) not null, entrada_prazo_dias integer not null,
    primeira_parcela_dias integer not null, permite_multiplos_contratos boolean not null,
    bloqueia_contrato_juridico boolean not null, validade_proposta_dias integer not null,
    tolerancia_parcela_dias integer not null, parcelas_vencidas_para_quebra integer not null,
    perde_desconto_na_quebra boolean not null, permite_renegociacao boolean not null,
    maximo_renegociacoes integer not null, publicada_em timestamp(6) with time zone not null,
    publicada_por varchar(150) not null, constraint uk_politica_financeira_versao unique (versao)
);

create unique index uk_politica_financeira_vigente on politicas_financeiras (vigente) where vigente = true;

create table alcadas_desconto (
    id bigint generated by default as identity primary key, politica_id bigint not null,
    perfil varchar(30) not null, percentual_maximo numeric(9,6) not null, valor_maximo numeric(19,2),
    permite_principal boolean not null, permite_juros boolean not null, permite_multa boolean not null,
    exige_aprovacao boolean not null,
    constraint fk_alcada_politica foreign key (politica_id) references politicas_financeiras,
    constraint uk_alcada_politica_perfil unique (politica_id, perfil)
);
