create table acordos_financeiros (
 id bigint generated by default as identity primary key, politica_id bigint not null, protocolo varchar(50) not null,
 status varchar(30) not null, principal_original numeric(19,2) not null, juros numeric(19,2) not null,
 multa numeric(19,2) not null, desconto numeric(19,2) not null, valor_entrada numeric(19,2) not null,
 valor_negociado numeric(19,2) not null, quantidade_parcelas integer not null, criado_em timestamp with time zone not null,
 valido_ate timestamp with time zone not null, criado_por varchar(150) not null, solicitado_em timestamp with time zone,
 decidido_em timestamp with time zone, decidido_por varchar(150), justificativa varchar(1000), motivo_decisao varchar(1000),
 versao bigint not null default 0, constraint uk_acordo_protocolo unique(protocolo),
 constraint fk_acordo_politica foreign key(politica_id) references politicas_financeiras
);
create table acordo_itens (
 id bigint generated by default as identity primary key, acordo_id bigint not null, cobranca_id bigint not null,
 principal numeric(19,2) not null, juros numeric(19,2) not null, multa numeric(19,2) not null,
 desconto numeric(19,2) not null, total numeric(19,2) not null,
 constraint fk_item_acordo foreign key(acordo_id) references acordos_financeiros,
 constraint fk_item_cobranca foreign key(cobranca_id) references cobrancas
);
create table parcelas_acordo (
 id bigint generated by default as identity primary key, acordo_id bigint not null, numero integer not null,
 vencimento date not null, principal numeric(19,2) not null, juros numeric(19,2) not null, multa numeric(19,2) not null,
 total numeric(19,2) not null, valor_pago numeric(19,2) not null default 0, status varchar(20) not null,
 constraint fk_parcela_acordo foreign key(acordo_id) references acordos_financeiros,
 constraint uk_parcela_acordo_numero unique(acordo_id, numero)
);
