create table pagamentos_financeiros(
 id bigint generated by default as identity primary key,cobranca_id bigint not null,acordo_id bigint,comprovante_id bigint not null,
 valor numeric(19,2) not null,credito_excedente numeric(19,2) not null default 0,data_pagamento date not null,
 status varchar(20) not null,origem varchar(20) not null,referencia_externa varchar(150),chave_idempotencia varchar(100) not null,
 registrado_em timestamp with time zone not null,registrado_por varchar(150) not null,confirmado_em timestamp with time zone,
 confirmado_por varchar(150),observacao varchar(1000),constraint uk_pagamento_chave unique(chave_idempotencia),
 constraint fk_pagamento_cobranca foreign key(cobranca_id) references cobrancas,
 constraint fk_pagamento_acordo foreign key(acordo_id) references acordos_financeiros,
 constraint fk_pagamento_comprovante foreign key(comprovante_id) references atendimento_anexos
);
create table pagamento_alocacoes(
 id bigint generated by default as identity primary key,pagamento_id bigint not null,parcela_id bigint,
 multa numeric(19,2) not null,juros numeric(19,2) not null,principal numeric(19,2) not null,total numeric(19,2) not null,
 constraint fk_alocacao_pagamento foreign key(pagamento_id) references pagamentos_financeiros,
 constraint fk_alocacao_parcela foreign key(parcela_id) references parcelas_acordo
);
