-- Repara bancos em que a migration V5 consta no historico do Flyway,
-- mas a tabela acordo_itens foi removida ou nao chegou a ser criada.
-- O IF NOT EXISTS mantem esta migration segura para bancos integros.
create table if not exists acordo_itens (
    id bigint generated by default as identity primary key,
    acordo_id bigint not null,
    cobranca_id bigint not null,
    principal numeric(19,2) not null,
    juros numeric(19,2) not null,
    multa numeric(19,2) not null,
    desconto numeric(19,2) not null,
    total numeric(19,2) not null,
    constraint fk_item_acordo foreign key (acordo_id) references acordos_financeiros,
    constraint fk_item_cobranca foreign key (cobranca_id) references cobrancas
);
