package br.com.w4solution.cob4.services.financeiro;
import br.com.w4solution.cob4.domain.*;import br.com.w4solution.cob4.dto.financeiro.CriarAcordoDTO;import br.com.w4solution.cob4.repositories.*;import br.com.w4solution.cob4.security.*;
import org.junit.jupiter.api.Test;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.Mock;import org.mockito.junit.jupiter.MockitoExtension;
import java.math.BigDecimal;import java.time.LocalDate;import java.util.*;import static org.assertj.core.api.Assertions.assertThat;import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class AcordoFinanceiroServiceTests{
	@Mock AcordoFinanceiroRepository acordos;@Mock CobrancaRepository cobrancas;@Mock PoliticaFinanceiraRepository politicas;@Mock UsuarioAtualService usuarios;
	@Test void calculaJurosMultaParcelasEVinculaVersaoDaPolitica(){PoliticaFinanceira p=politica();Cobranca c=new Cobranca();c.setReferencia("COB-1");c.setValorTotal(new BigDecimal("100.00"));c.setDiasAtraso(30);c.setEstadoFluxo("EM_ATENDIMENTO");
		when(politicas.findByVigenteTrue()).thenReturn(Optional.of(p));when(cobrancas.findByReferencia("COB-1")).thenReturn(Optional.of(c));when(usuarios.atual()).thenReturn(new UsuarioAutenticado(1L,"Admin","admin",PerfilUsuario.ADMINISTRADOR));
		var service=new AcordoFinanceiroService(acordos,cobrancas,politicas,usuarios);var r=service.simular(new CriarAcordoDTO(List.of("COB-1"),BigDecimal.ZERO,BigDecimal.ZERO,2,LocalDate.now().plusDays(10),"Teste"));
		assertThat(r.principal()).isEqualByComparingTo("100.00");assertThat(r.juros()).isEqualByComparingTo("1.00");assertThat(r.multa()).isEqualByComparingTo("2.00");assertThat(r.valorNegociado()).isEqualByComparingTo("103.00");assertThat(r.parcelas()).hasSize(2);assertThat(r.politicaVersao()).isEqualTo(7);assertThat(r.status()).isEqualTo("APROVADO");}
	private PoliticaFinanceira politica(){PoliticaFinanceira p=new PoliticaFinanceira();p.setVersao(7);p.setJurosTipo(PoliticaFinanceira.TipoJuros.SIMPLES);p.setJurosPercentual(BigDecimal.ONE);p.setJurosPeriodicidade(PoliticaFinanceira.PeriodicidadeJuros.MENSAL);p.setJurosInicio(PoliticaFinanceira.InicioEncargos.DIA_SEGUINTE);p.setMultaTipo(PoliticaFinanceira.TipoMulta.PERCENTUAL);p.setMultaValor(new BigDecimal("2"));p.setMultaInicio(PoliticaFinanceira.InicioEncargos.DIA_SEGUINTE);p.setCasasDecimais(2);p.setMetodoArredondamento(PoliticaFinanceira.MetodoArredondamento.MEIO_PARA_CIMA);p.setMaximoParcelas(12);p.setValorMinimoParcela(BigDecimal.ONE);p.setIntervaloParcelasDias(30);p.setAjusteDiaNaoUtil(PoliticaFinanceira.AjusteDiaNaoUtil.PROXIMO_DIA_UTIL);p.setEntradaPercentualMinimo(BigDecimal.ZERO);p.setEntradaValorMinimo(BigDecimal.ZERO);p.setPermiteMultiplosContratos(true);p.setValidadePropostaDias(7);AlcadaDesconto a=new AlcadaDesconto();a.setPolitica(p);a.setPerfil(PerfilUsuario.ADMINISTRADOR);a.setPercentualMaximo(new BigDecimal("100"));p.getAlcadas().add(a);return p;}
}
