package br.com.w4solution.cob4.security;

public enum AcaoSistema {
	MOVIMENTAR_PROTOCOLO, ENCERRAR_PROTOCOLO, REABRIR_PROTOCOLO, CONFIGURAR_SISTEMA,
	CONFIRMAR_PAGAMENTO, EXECUTAR_CAMPO, ACESSAR_JURIDICO, EXPORTAR_DADOS, ANONIMIZAR_DADOS,
	DISTRIBUIR_CARTEIRA
}
