export const DATA = [{
  id: 'gTpq3k',
  name: 'Lily Collins',
  position: 'Designer',
  team: 10,
  experience: '3 years',
  phone: '+00578115245',
  avatar: '/static/avatar/001-man.svg',
  dateOfBirth: 'Dec 02, 2021',
  email: 'Uilib@gmail.com',
  address: 'Corner View, Sylhet',
  status: 'Full Time'
}, {
  id: 'qZ8kYo',
  name: 'Lily Callins',
  position: 'Editor',
  team: 25,
  experience: '2 years',
  phone: '+00578156245',
  avatar: '/static/avatar/002-girl.svg',
  dateOfBirth: 'Dec 02, 2021',
  email: 'editor@gmail.com',
  address: 'Mirpur, Dhaka',
  status: 'Remote'
}, {
  id: 'F_ZYnS',
  name: 'Lily Collins',
  position: 'Designer',
  team: 5,
  experience: '5 years',
  phone: '+00578134245',
  avatar: '/static/avatar/003-boy.svg',
  dateOfBirth: 'Dec 02, 2021',
  email: 'desy@gmail.com',
  address: 'New Market, Chittagong',
  status: 'Part Time'
}, {
  id: 'u2iJgo',
  name: 'Selena Smith',
  position: 'Developer',
  team: 11,
  experience: '7 years',
  phone: '+00574115645',
  avatar: '/static/avatar/004-woman.svg',
  dateOfBirth: 'Nov 05, 2021',
  email: 'smith@gmail.com',
  address: 'Gulshan, Dhaka',
  status: 'Full Time'
}, {
  id: 'PwLvOI',
  name: 'Lily Collins',
  position: 'Developer',
  team: 17,
  experience: '3 years',
  phone: '+00578115245',
  avatar: '/static/avatar/005-man-1.svg',
  dateOfBirth: 'Nov 05, 2021',
  email: 'Uilib@gmail.com',
  address: 'Corner View, Sylhet',
  status: 'Full Time'
}, {
  id: 'TbpU3n',
  name: 'Lily Collins',
  position: 'Designer',
  team: 30,
  experience: '3 years',
  phone: '+00578115245',
  avatar: '/static/avatar/001-man.svg',
  dateOfBirth: 'Dec 02, 2021',
  email: 'Uilib@gmail.com',
  address: 'Corner View, Sylhet',
  status: 'Full Time'
}, {
  id: 'RU3elJ',
  name: 'Lily Callins',
  position: 'Editor',
  team: 22,
  experience: '3 years',
  phone: '+00578115245',
  avatar: '/static/avatar/002-girl.svg',
  dateOfBirth: 'Dec 02, 2021',
  email: 'Uilib@gmail.com',
  address: 'Corner View, Sylhet',
  status: 'Full Time'
}, {
  id: '790pv9',
  name: 'Lily Collins',
  position: 'Designer',
  team: 33,
  experience: '3 years',
  phone: '+00578115245',
  avatar: '/static/avatar/003-boy.svg',
  dateOfBirth: 'Dec 02, 2021',
  email: 'Uilib@gmail.com',
  address: 'Corner View, Sylhet',
  status: 'Full Time'
}, {
  id: 'wHVOFv',
  name: 'Lily Collins',
  position: 'Developer',
  team: 41,
  experience: '3 years',
  phone: '+00578115245',
  avatar: '/static/avatar/004-woman.svg',
  dateOfBirth: 'Nov 05, 2021',
  email: 'Uilib@gmail.com',
  address: 'Corner View, Sylhet',
  status: 'Full Time'
}, {
  id: 'pzReLn',
  name: 'Lily Collins',
  position: 'Developer',
  team: 13,
  experience: '3 years',
  phone: '+00578115245',
  avatar: '/static/avatar/005-man-1.svg',
  dateOfBirth: 'Nov 05, 2021',
  email: 'Uilib@gmail.com',
  address: 'Corner View, Sylhet',
  status: 'Full Time'
}, {
  id: 'ZNwQPJ',
  name: 'Lily Collins',
  position: 'Designer',
  team: 8,
  experience: '3 years',
  phone: '+00578115245',
  avatar: '/static/avatar/001-man.svg',
  dateOfBirth: 'Dec 02, 2021',
  email: 'Uilib@gmail.com',
  address: 'Corner View, Sylhet',
  status: 'Full Time'
}, {
  id: 'Q2axdR',
  name: 'Lily Callins',
  position: 'Editor',
  team: 6,
  experience: '3 years',
  phone: '+00578115245',
  avatar: '/static/avatar/002-girl.svg',
  dateOfBirth: 'Dec 02, 2021',
  email: 'Uilib@gmail.com',
  address: 'Corner View, Sylhet',
  status: 'Full Time'
}, {
  id: '4YO0gT',
  name: 'Lily Collins',
  position: 'Designer',
  team: 4,
  experience: '3 years',
  phone: '+00578115245',
  avatar: '/static/avatar/003-boy.svg',
  dateOfBirth: 'Dec 02, 2021',
  email: 'Uilib@gmail.com',
  address: 'Corner View, Sylhet',
  status: 'Full Time'
}, {
  id: '1uz_fB',
  name: 'Lily Collins',
  position: 'Developer',
  team: 17,
  experience: '3 years',
  phone: '+00578115245',
  avatar: '/static/avatar/004-woman.svg',
  dateOfBirth: 'Nov 05, 2021',
  email: 'Uilib@gmail.com',
  address: 'Corner View, Sylhet',
  status: 'Full Time'
}, {
  id: 'gRu3Pd',
  name: 'Lily Collins',
  position: 'Developer',
  team: 19,
  experience: '3 years',
  phone: '+00578115245',
  avatar: '/static/avatar/005-man-1.svg',
  dateOfBirth: 'Nov 05, 2021',
  email: 'Uilib@gmail.com',
  address: 'Corner View, Sylhet',
  status: 'Full Time'
}];