spring.jpa.hibernate.ddl-auto=validate
sgc.demo.dados-ficticios=false
sgc.security.cookie.secure=true
management.endpoint.health.show-details=never
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
logging.structured.format.console=logstash
