spring.application.name=cob4
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:}
spring.datasource.username=${POSTGRES_USER:}
spring.datasource.password=${POSTGRES_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.error.include-stacktrace=never
api.service.integration.rbx=${RBX_API_URL:}
api.service.integration.rbx.v2=${RBX_API_V2_URL:}
api.service.integration.rbx.chave=${RBX_API_KEY:}
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
