package br.com.w4solution.cob4.services.financeiro;
import br.com.w4solution.cob4.domain.*;import br.com.w4solution.cob4.repositories.*;
import com.lowagie.text.Document;import com.lowagie.text.Paragraph;import com.lowagie.text.pdf.PdfWriter;import org.apache.poi.ss.usermodel.*;import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.io.*;import java.nio.charset.StandardCharsets;import java.time.*;import java.util.*;
@Service public class ExportacaoFinanceiraService{
	private final FechamentoMensalRepository fechamentos;private final PagamentoFinanceiroRepository pagamentos;
	public ExportacaoFinanceiraService(FechamentoMensalRepository f,PagamentoFinanceiroRepository p){fechamentos=f;pagamentos=p;}
	@Transactional(readOnly=true) public byte[] csv(Long id){var f=fechamento(id);StringBuilder s=new StringBuilder("pagamento_id;cobranca;data;valor;status;origem;referencia_externa\n");for(var p:pagamentos(f))s.append(p.getId()).append(';').append(p.getCobranca().getReferencia()).append(';').append(p.getDataPagamento()).append(';').append(p.getValor()).append(';').append(p.getStatus()).append(';').append(p.getOrigem()).append(';').append(seguro(p.getReferenciaExterna())).append('\n');return s.toString().getBytes(StandardCharsets.UTF_8);}
	@Transactional(readOnly=true) public byte[] xlsx(Long id){var f=fechamento(id);try(var w=new XSSFWorkbook();var out=new ByteArrayOutputStream()){Sheet resumo=w.createSheet("Resumo");Object[][] linhas={{"Competencia",f.getCompetencia()},{"Versao",f.getVersao()},{"Status",f.getStatus()},{"Pagamentos",f.getTotalPagamentos()},{"Estornos",f.getTotalEstornos()},{"Descontos",f.getTotalDescontos()},{"Juros",f.getTotalJuros()},{"Multas",f.getTotalMultas()},{"Divergencias",f.getDivergenciasAbertas()}};for(int i=0;i<linhas.length;i++){Row r=resumo.createRow(i);r.createCell(0).setCellValue(String.valueOf(linhas[i][0]));r.createCell(1).setCellValue(String.valueOf(linhas[i][1]));}Sheet det=w.createSheet("Pagamentos");String[] h={"ID","Cobranca","Data","Valor","Status","Origem","Referencia"};Row hr=det.createRow(0);for(int i=0;i<h.length;i++)hr.createCell(i).setCellValue(h[i]);int n=1;for(var p:pagamentos(f)){Row r=det.createRow(n++);r.createCell(0).setCellValue(p.getId());r.createCell(1).setCellValue(p.getCobranca().getReferencia());r.createCell(2).setCellValue(p.getDataPagamento().toString());r.createCell(3).setCellValue(p.getValor().doubleValue());r.createCell(4).setCellValue(p.getStatus().name());r.createCell(5).setCellValue(p.getOrigem().name());r.createCell(6).setCellValue(seguro(p.getReferenciaExterna()));}w.write(out);return out.toByteArray();}catch(Exception e){throw new IllegalStateException("Falha ao gerar XLSX",e);}}
	@Transactional(readOnly=true) public byte[] pdf(Long id){var f=fechamento(id);try(var out=new ByteArrayOutputStream()){Document d=new Document();PdfWriter.getInstance(d,out);d.open();d.add(new Paragraph("Fechamento financeiro "+f.getCompetencia()+" - versao "+f.getVersao()));d.add(new Paragraph("Status: "+f.getStatus()));d.add(new Paragraph("Pagamentos: R$ "+f.getTotalPagamentos()));d.add(new Paragraph("Estornos: R$ "+f.getTotalEstornos()));d.add(new Paragraph("Descontos: R$ "+f.getTotalDescontos()));d.add(new Paragraph("Juros: R$ "+f.getTotalJuros()));d.add(new Paragraph("Multas: R$ "+f.getTotalMultas()));d.add(new Paragraph("Divergencias abertas: "+f.getDivergenciasAbertas()));d.add(new Paragraph("Gerado por "+f.getGeradoPor()+" em "+f.getGeradoEm()));d.close();return out.toByteArray();}catch(Exception e){throw new IllegalStateException("Falha ao gerar PDF",e);}}
	private FechamentoMensal fechamento(Long id){return fechamentos.findById(id).orElseThrow(()->new IllegalArgumentException("Fechamento nao encontrado"));}
	private List<PagamentoFinanceiro> pagamentos(FechamentoMensal f){YearMonth m=YearMonth.parse(f.getCompetencia());return pagamentos.findByDataPagamentoBetweenAndStatusIn(m.atDay(1),m.atEndOfMonth(),Arrays.asList(PagamentoFinanceiro.Status.values()));}
	private String seguro(String v){return v==null?"":v.replace(";",",").replace("\n"," ").replace("\r"," ");}
}
